
x-base-app: &base-app
  build: .
  working_dir: /app/src
  environment:
    - PYTHONPATH=/app
  env_file:
    - .env
  restart: unless-stopped

services:
  # --- API ---
  api:
    <<: *base-app 
    container_name: media_api

  # --- Celery ---
  worker:
    <<: *base-app  
    container_name: media_worker

volumes:
  postgres_data:
  minio_data:
